version: '3'

services:
  app:
    build: .
    depends_on:
      db_mysql:
        condition: service_healthy
    ports:
      - "5010:5010"
    networks:
      - app_layer
    environment:
      - DB_HOST=db_mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=music

  redis:
    image: redis:latest
    networks:
      - app_network

  nginx:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - app_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  app_network:
    driver: bridge
