apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-be-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exam-be-deployment
  template:
    metadata:
      labels:
        app: exam-be-deployment
    spec:
      containers:
      - name: hanil-be
        image: frenzy669/hanil-be-repo:latest
        env:
        - name: MYSQL_HOST
          value: "exam-mysql-clusterip"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "123456"
        - name: MYSQL_NAME
          value: "crypto_db"

        ports:
        - containerPort: 5001
        
---
apiVersion: v1
kind: Service
metadata:
  name: exam-be-clusterip
spec:
  type: ClusterIP
  selector:
    app: exam-be-deployment
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001