apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort # No need to use LB OR BROWSE THE APPLICATION 
  ports:
    - port: 5003
      targetPort: 5003
  selector:
    app: fe

